### PR TITLE
foreman all the things

### PR DESCRIPTION
**Pull request by cdmwebs**
I added some stuff to let me run pg per-application and foreman hotness, too.

I'm also trying to be a good citizen and use pull requests, even though no one will read this, respond, or act on it.

### CODE REVIEW

**Comment by queso** [comment]
I dig it, I will sign off on it.

**Comment by cdmwebs** [comment]
Ha! I knew that last sentence would strike a nerve somewhere!

**Comment by queso** [comment]
:trollface:

**Comment by st23am** [comment]
+1 Cool story bro

**Comment by cdmwebs** [comment]
all

**Comment by cdmwebs** [comment]
y u no

**Comment by queso** [comment]
For the record, we should all pull request shit!

Pull Requests

**Comment by cdmwebs** [comment]
ggg

**Pull request merged**
